/**
 * Rebuilds the fake demo dataset behind the README screenshots.
 *
 * Run it with `npm run demo:seed` (or via `npm run screenshots`, which seeds
 * and then captures). Everything below is invented — no real merchant,
 * account, or amount appears anywhere in it.
 *
 * ## Where this writes
 *
 * `data/demo/demo.db`, never `data/app.db`. Two reasons, both learned the hard
 * way elsewhere in this repo (see the comment block in playwright.config.ts):
 *
 *   1. This script DROPS its database and rebuilds it from nothing. Pointed at
 *      the live file that is a total loss of the user's financial history, so
 *      the live file must be unreachable from here by construction, not by
 *      remembering to set an env var. Hence the default below and the
 *      assertion in `assertDisposableTarget`.
 *   2. It gets its own *directory*, not just its own filename, because
 *      `exportRules()` mirrors preferences.json next to the resolved database
 *      file rather than next to DATABASE_URL. A demo db sitting directly in
 *      `data/` could therefore overwrite the real `data/preferences.json`.
 *
 * ## Why the numbers are what they are
 *
 * The shape is pinned to `docs/screenshots/accounts.png`, which is not
 * regenerated by the capture script (that page shows no category colors, so a
 * theme change never invalidates it). Same three accounts, same per-account
 * counts (86 / 40 / 65 = 191), same Jul 2025 – Jun 2026 window. Change those
 * and accounts.png quietly starts lying about the app.
 */
import fs from 'fs';
import path from 'path';

// Set BEFORE the db client resolves anything. Safe as a plain statement even
// though imports hoist above it: getDb() is lazy and memoizes on first call,
// and nothing in this module's import graph calls it at import time.
// `assertDisposableTarget` re-checks the resolved path at runtime regardless,
// so an eager caller introduced later still cannot reach the live database.
process.env.DATABASE_URL ??= 'file:./data/demo/demo.db';

import { resolveDbFile } from '@/db/client';
import { runMigrations } from '@/db/migrate';
import { ingestClassifiedBatch, type IngestTxn } from '@/lib/ingest';

/** Abort unless the resolved database is one this script may destroy. */
function assertDisposableTarget(): string {
  const file = resolveDbFile();
  const dir = path.basename(path.dirname(file));
  if (dir !== 'demo') {
    throw new Error(
      `Refusing to seed ${file}.\n` +
        'This script deletes its database and rebuilds it. It will only touch a\n' +
        "file inside a directory named 'demo' (default: data/demo/demo.db).\n" +
        'Unset DATABASE_URL, or point it at a demo directory.',
    );
  }
  return file;
}

// Deterministic PRNG: rerunning reproduces byte-identical screenshots, so a
// refresh diffs as "the theme changed", not "the fake data moved around too".
let seedState = 20260814;
const rand = () => {
  seedState = (seedState * 1664525 + 1013904223) % 4294967296;
  return seedState / 4294967296;
};

const MONTHS: string[] = [];
for (let i = 6; i < 12; i++) MONTHS.push(`2025-${String(i + 1).padStart(2, '0')}`);
for (let i = 0; i < 6; i++) MONTHS.push(`2026-${String(i + 1).padStart(2, '0')}`);

const day = (d: number) => String(d).padStart(2, '0');

/**
 * `count` amounts that vary but sum to exactly `total`, so category totals land
 * on the round figures the charts label.
 */
function split(total: number, count: number): number[] {
  const weights = Array.from({ length: count }, () => 0.75 + rand() * 0.5);
  const sum = weights.reduce((a, b) => a + b, 0);
  const out = weights.map((w) => Math.round(((total * w) / sum) * 100) / 100);
  const drift = Math.round((total - out.reduce((a, b) => a + b, 0)) * 100) / 100;
  out[out.length - 1] = Math.round((out[out.length - 1] + drift) * 100) / 100;
  return out;
}

/**
 * Spread `count` transactions over the 12 months, cycling merchants.
 *
 * A count that divides evenly into 12 is treated as a recurring bill (rent,
 * electric, a streaming plan) and cycles the months in order — one per month.
 * Everything else scatters at random. Cycling the one-offs too piles every
 * single-instance category (the 3 flights, the 2 pharmacy runs) into the first
 * months of the range, which rendered as a spending line sloping steadily
 * downhill for no reason a reader could infer.
 */
function spend(
  count: number,
  total: number,
  categoryId: string,
  subcategoryId: string,
  merchants: string[],
): IngestTxn[] {
  const recurring = count % MONTHS.length === 0;
  return split(total, count).map((amount, i) => ({
    date: `${
      recurring ? MONTHS[i % MONTHS.length] : MONTHS[Math.floor(rand() * MONTHS.length)]
    }-${day(2 + Math.floor(rand() * 26))}`,
    description: merchants[i % merchants.length],
    amount: -amount,
    categoryId,
    subcategoryId,
  }));
}

// Joint · Ally — 12 rent + 24 semi-monthly paychecks + 4 odds and ends = 40.
const ally: IngestTxn[] = [];
for (const month of MONTHS) {
  ally.push({
    date: `${month}-01`,
    description: 'SUNSET RIDGE APARTMENTS',
    amount: -2650,
    categoryId: 'housing',
    subcategoryId: 'rent',
  });
  for (const d of ['15', '28']) {
    ally.push({
      date: `${month}-${d}`,
      description: 'GLOBEX DIRECT DEP',
      amount: 4029,
      categoryId: 'income',
      subcategoryId: 'salary',
    });
  }
}
ally.push(
  ...spend(4, 620, 'financial', 'bank-fees', [
    'ALLY ANNUAL FEE',
    'WIRE TRANSFER FEE',
    'SAFE DEPOSIT BOX',
    'CASHIERS CHECK',
  ]),
);

// Alex · Chase — 50 food + 18 transport + 12 entertainment + 3 travel
//                + 2 healthcare + 1 shopping = 86.
const chase: IngestTxn[] = [
  ...spend(26, 1980, 'food', 'grocery', [
    'WHOLE FOODS MKT 4412',
    'TRADER JOES #217',
    'SAFEWAY #1180',
    'BERKELEY BOWL',
  ]),
  ...spend(16, 940, 'food', 'restaurant', [
    'TARTINE BAKERY',
    'NOPA RESTAURANT',
    'ZUNI CAFE',
    'LITTLE STAR PIZZA',
  ]),
  ...spend(8, 269, 'food', 'coffee', ['BLUE BOTTLE COFFEE', 'PEETS COFFEE #338', 'RITUAL COFFEE']),
  ...spend(12, 640, 'transportation', 'fuel', ['SHELL OIL 574', 'CHEVRON 0092', 'ARCO #4417']),
  ...spend(6, 338, 'transportation', 'transit', ['BART CLIPPER RELOAD', 'MUNI MOBILE']),
  ...spend(12, 330, 'entertainment', 'streaming', [
    'NETFLIX.COM',
    'SPOTIFY USA',
    'MAX STREAMING',
    'DISNEY PLUS',
  ]),
  ...spend(3, 353, 'travel', 'flights', ['ALASKA AIR 0271', 'SOUTHWEST AIR', 'UNITED 0162']),
  ...spend(2, 90, 'healthcare', 'pharmacy', ['WALGREENS #7712', 'CVS PHARMACY 3390']),
  ...spend(1, 64, 'shopping', 'clothing', ['UNIQLO SF UNION SQ']),
];

// Sam · Amex — 22 food + 14 personal care + 24 utilities + 5 shopping = 65.
const amex: IngestTxn[] = [
  ...spend(22, 500, 'food', 'delivery', ['DOORDASH', 'INSTACART', 'UBER EATS']),
  ...spend(12, 1740, 'personal-care', 'gym', ['EQUINOX SF', 'YOGA FLOW SF']),
  ...spend(2, 840, 'personal-care', 'haircut', ['EDO SALON', 'BARBER LOUNGE']),
  ...spend(12, 1109, 'utilities', 'electric', ['PG&E UTILITIES']),
  ...spend(12, 628, 'utilities', 'internet', ['MONKEYBRAINS INTERNET', 'SONIC.NET']),
  ...spend(5, 347, 'shopping', 'home-goods', ['TARGET 2718', 'IKEA EMERYVILLE', 'ACE HARDWARE']),
];

const BATCHES = [
  { owner: 'Alex', institution: 'Chase', name: 'Sapphire', mask: '4417', txns: chase },
  { owner: 'Joint', institution: 'Ally', name: 'Checking', mask: '8820', txns: ally },
  { owner: 'Sam', institution: 'Amex', name: 'Everyday', mask: '1004', txns: amex },
];

async function main(): Promise<void> {
  const file = assertDisposableTarget();

  // Start from nothing: ingest's fingerprint dedupe would otherwise skip every
  // row on a rerun, leaving whatever the previous run produced in place.
  for (const suffix of ['', '-shm', '-wal']) fs.rmSync(`${file}${suffix}`, { force: true });
  fs.mkdirSync(path.dirname(file), { recursive: true });
  runMigrations();

  let total = 0;
  for (const b of BATCHES) {
    const { added } = await ingestClassifiedBatch({
      account: {
        institution: b.institution,
        name: b.name,
        owner: b.owner,
        mask: b.mask,
        accountClass: 'spending',
        type: b.institution === 'Amex' ? 'credit' : 'depository',
      },
      source: 'manual',
      transactions: b.txns,
    });
    total += added;
    // eslint-disable-next-line no-console
    console.log(`  ${b.owner} ${b.institution} ${b.name}: ${added} transactions`);
  }
  // eslint-disable-next-line no-console
  console.log(`Seeded ${total} demo transactions into ${path.relative(process.cwd(), file)}`);
}

void main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
